apiVersion: v1  # Specifies the API version for the Service resource
kind: Service  # Defines the type of Kubernetes resource
metadata:
  name: api  # The name of the Service
  namespace: local  # The namespace where the Service is created
  labels:
    app: api  # Labels for the Service, useful for selectors
spec:
  type: NodePort  # Change service type to NodePort for external access
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.port }}   # Specify a node port for external access (30001 is an example)
      name: http
  selector:
    app: api