apiVersion: networking.istio.io/v1alpha3  # Specifies the API version for the VirtualService resource
kind: VirtualService  # Defines the type of Kubernetes resource
metadata:
  name: api  # The name of the VirtualService
  namespace: local  # The namespace where the VirtualService is created
spec:
  hosts:
    - "*"  # The hosts that the VirtualService will serve
  gateways:
    - api-gateway  # The Gateway that the VirtualService will use
  http:
    - route:
        - destination:
            host: api  # The name of the Service that traffic will be routed to
            port:
              number: 8080  # The port of the Service that traffic will be routed to
