---
# Source: myapp/templates/configMap.yaml
# configMap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-properties
data:
    application.properties: "application.name=myapp\napplication.version=1.0.0\n"
    myapp.greeting: "Hello, World!"
---
# Source: myapp/templates/service.yaml
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: myapp
---
# Source: myapp/templates/deployment.yaml
# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: anacondong/myapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myapp-properties
