apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
    - {{ .Values.app.name }}
  http:
    - route:
        - destination:
            host: {{ .Values.app.name }}
            subset: v1